query ($date: DateTime!) {
  viewer {
    contributionsCollection(from: $date) {
      totalCommitContributions
      pullRequestContributions(first: 100) {
        nodes {
          pullRequest {
            repository {
              nameWithOwner
            }
          }
        }
      }
    }
  }
}
