{
  viewer {
    repositories(first: 100, isFork: false, isArchived: false, privacy: PUBLIC) {
      nodes {
        nameWithOwner
        languages(first: 5) {
          edges {
            size
            node {
              name
              color
            }
          }
        }
      }
    }
  }
}
