# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "56 2 * * *"}]
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.20
        with:
          template: markdown
          filename: README.md
          markdown: https://raw.githubusercontent.com/AllanChain/AllanChain/main/template.md
          config_output: markdown
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: AllanChain
          base: header, metadata
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
